name: Build and Deploy Webpages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Webpages
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # 选择要使用的 pnpm 版本
          version: 7
          # 使用 pnpm 安装依赖
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 18
          # 缓存 pnpm 依赖
          cache: pnpm

      # 运行构建脚本
      - name: Build VuePress site
        run: pnpm docs:build
        
      - name: Upload built webpages to our web server
        uses: appleboy/scp-action@v0.1.3
        with:
          rm: "true" ## remove target folder before upload data
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: ${{ secrets.SOURCE }}
          target: ${{ secrets.TARGET }}
          username: ${{ secrets.USERNAME }}
