name: Build and Deploy Webpages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Webpages
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
            
      - name: Cache dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-3-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-3-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        
      - name: Install CJK Fonts to Export PDF
        run: sudo apt install xfonts-encodings xfonts-utils && git clone https://github.com/ykla/ttf-mswin11-zh-deb && cd ttf-mswin11-zh-deb && sudo dpkg -i ttf-ms-win11-*.deb
        
      - name: Build VuePress site
        run: yarn docs:build && yarn docs:export
        

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::FreeBSD-Handbook-CN_$(date +"%Y.%m.%d_%H-%M")"
      - name: Release 
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: "docs/.vuepress/dist/vuepress-*.pdf"
     
      - name: Sync PDF file name to FreeBSD-Handbook-CN.pdf
        run: mv docs/.vuepress/dist/vuepress-*.pdf docs/.vuepress/dist/FreeBSD-handbook-cn.pdf

      - name: Upload built webpages to our web server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: ${{ secrets.SOURCE }}
          target: ${{ secrets.TARGET }}
          username: ${{ secrets.USERNAME }}
